### ISSUE TITLE
As a logged-in user (Expert), I want to choose one of three post creation options (article, video or note), so that I can share reliable information with users.

### ISSUE THREAD

**Issue by KarkabsisV** [ita-social-projects/dokazovi-be#126]
Logged-in user will have the opportunity to choose one of three proposed variants to create his post. 
There is a drop-down list.
When user will choose one and press on it, the typical pattern will appears on the page.

Acceptance Criteria:
1. There is a drop-down list with options.
2. User can see the options of the article when clicking on the drop-down list.
3. In the drop-down list, user can select only 1 of the proposed options:
- create an article,
- create a note,
- create a video.

![image](https://user-images.githubusercontent.com/75980615/102503294-3e4e9780-4088-11eb-8f20-e8f26a0d67ed.png)

4. After choosing an article option, the template for creation opens the article creation page
5. After choosing a note option, the template for creation opens the note creation page
6. After choosing a video option, the template for creation opens the video creation page

**Comment by EleonoraBudanova** [comment]
As a logged-in user(Expert), I want to choose one of three post creation options (article, video or note), so that I can share reliable information with users.
![image](https://user-images.githubusercontent.com/75980615/102500728-4c4ee900-4085-11eb-901d-cfbbed78cf3a.png)

**Precondition.**
User is already logged-in as Expert.

**Acceptance Criteria.**
1. Option of the article when clicking on the drop-down list.
2. In the drop-down list, you can select only 1 of the proposed options::
- create an article,
- create a note,
- create a video.
3. After choosing an article option, the template for creation opens below on the same page.

**Out of Scope.**
Confirmation request “Are you sure you want to create an article”.

**Comment by vitaliyhere** [comment]
BA check 18/07/21 
Accepted.
